# Generated by Django 5.2.10 on 2026-02-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='date_posted',
        ),
    ]
